#!/bin/bash

# First Batch file create by mikecote355@outlook.com
# Use without warrrty and at our risk.
# This a script to complete the install process of Unifi on Unbuntu 16.X version only


echo 'deb http://www.ubnt.com/downloads/unifi/debian stable ubiquiti' | sudo tee -a /etc/apt/sources.list.d/100-ubnt.list
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv C0A52C50 && sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10
sudo apt-get update
echo "Apt Get update complete"
sudo apt-get install default-jre -y
sudo apt-get install unifi -y
echo "unifi install complete"

sudo apt-get update
sudo apt-get install software-properties-common -y
sudo add-apt-repository universe
sudo add-apt-repository ppa:certbot/certbot
sudo apt-get update
sudo apt-get install certbot python-certbot-apache -y 
echo "lets-Encrypt installed"
sudo certbot --apache

cd /usr/local/bin 
wget https://raw.githubusercontent.com/mikecote355/Linux-unifi/master/unifi_ssl_import.sh
READ UNIFI_HOSTNAME
sudo sed -i 's/UNIFI_HOSTNAME=hostname.example.com/UNIFI_HOSTNAME=$UNIFI_HOSTNAME/g' /usr/local/bin/unifi_ssl_import.sh > /usr/local/bin/unifi_ssl_import.sh
chmod +x unifi_ssl_import
cd 
sudo unifi_ssl_import
echo "Install Complete"